# Generated by Django 6.0.1 on 2026-01-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
